name: CI Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-501:
    name: Launch Openfire 5.0.1
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Run Openfire
        uses: ./
        with:
          version: '5.0.1'

      - name: Check Admin Console
        run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != '/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi

  test-490:
    name: Launch Openfire 4.9.0
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v6

      - name: Run Openfire
        uses: ./
        with:
          version: '4.9.0'
            
      - name: Check Admin Console
        run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != 'http://127.0.0.1:9090/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi
            
  test-483:
    name: Launch Openfire 4.8.3
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v6

      - name: Run Openfire
        uses: ./
        with:
          version: '4.8.3'
            
      - name: Check Admin Console
        run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != 'http://127.0.0.1:9090/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi

  test-daily:
    name: Launch Openfire Daily
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v6

      - name: Run Openfire
        uses: ./
        with:
          daily: 'true'
            
      - name: Check Admin Console
        run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != '/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi
            

  test-plugin:
    name: Launch Openfire with Plugin
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v6

      - name: Download Plugin
        run: |
          curl https://igniterealtime.org/projects/openfire/plugins/1.8.0/xmldebugger.jar -o xmldebugger.jar

      - name: Run Openfire
        uses: ./
        with:
          version: '4.9.0'
          plugin: ./xmldebugger.jar
            
      - name: Check Admin Console
        run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != 'http://127.0.0.1:9090/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi
            